#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $BYRDS_REPO == "BygByrdBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9WYWRlci9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $BYRDS_REPO == "BygByrdbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9WYWRlci9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $BYRDS_REPO =~ $regex ]]
    then
        if [[ $BYRDS_REPO_BRANCH ]]
        then
            echo "${BYRDS_REPO}/archive/${BYRDS_REPO_BRANCH}.zip"
        else
            echo "${BYRDS_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9WYWRlci9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="BYRDS.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    HELLPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $HELLPATH
    echo "    Starting BYRD    "
    echo "

💥💥💥 💥      💥 💥💥💥   💥💥💥
💥   💥  💥  💥   💥    💥 💥    💥
💥💥💥     💥     💥💥💥   💥    💥
💥   💥    💥     💥 💥    💥    💥
💥💥💥     💥     💥   💥  💥💥💥






                      
                      
                      
                      
                             
                             

                              
                              
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
